### ISSUE TITLE
Python version crashes

### ISSUE THREAD

**Issue by lkarsten** [varnish/varnishgather#14]
lkarsten@immer:~/work/varnishgather$ python ./varnishgather.py 
Running date
Running dmesg
Running free -m
Running lsb_release -a
Running varnishstat -V
Running sysctl -a
Traceback (most recent call last):
  File "./varnishgather.py", line 142, in <module>
    LoggedCommand(cmd)(tar)
  File "./varnishgather.py", line 100, in **call**
    self.run()
  File "./varnishgather.py", line 95, in run
    p = Popen(self.command, stdout=PIPE, stderr=PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 679, in **init**
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1259, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
lkarsten@immer:~/work/varnishgather$ 
lkarsten@immer:~/work/varnishgather$ git log --oneline | head -n1
7da75b6 Add warning and sleep when run as non-root

**Comment by freshteapot** [comment]
No longer supporting the python port.
